all:
	mkdir -p bin
	g++ column-major.cpp -o bin/column-major -g -Wall -Wextra -pedantic -std=c++11
	g++ row-major.cpp -o bin/row-major -g -Wall -Wextra -pedantic -std=c++11
	g++ strassen.cpp -o bin/strassen -g -Wall -Wextra -pedantic -std=c++11