all:
	g++ column-major.cpp -o column-major -g -Wall -Wextra -pedantic -std=c++11
	g++ row-major.cpp -o row-major -g -Wall -Wextra -pedantic -std=c++11
	g++ strassen.cpp -o strassen -g -Wall -Wextra -pedantic -std=c++11